jobs:
  - job: BuildAndPublish
    displayName: 'Build and publish'
    steps:
    # Since the Angular application is inside the ClientApp folder, we first have to navigate there
    - script: |
        cd ./ClientApp
        npm install -g @angular/cli
        npm install
      displayName: 'Install Angular CLI and npm packages'

    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '18.x'
      
    # The ng build will create a dist folder with the build content
    - script: |
        cd ./ClientApp
        ng build --configuration production
      displayName: 'Build Angular Project'

    - task: CopyFiles@2
      displayName: 'Copy files from dist to artifactstagingdirectory'
      inputs:
        SourceFolder: './ClientApp/dist'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)' 

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts inside angularApp folder'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'angularApp'